# Generated by Django 5.1.5 on 2025-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
