# Generated by Django 5.1.5 on 2025-03-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
