# Generated by Django 5.1.5 on 2025-03-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('street_and_house', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
