# Generated by Django 5.1.5 on 2025-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_shippingdetails_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shipping_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
