# Generated by Django 5.1.5 on 2025-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_shipping_price_customuser_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shipping_price',
            field=models.FloatField(blank=True, default=3.0),
        ),
    ]
