# Generated by Django 5.1.5 on 2025-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_appropriate',
            field=models.BooleanField(default=True),
        ),
    ]
