# Generated by Django 5.1.5 on 2025-02-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_options_remove_cart_change_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenproduct',
            options={'ordering': ['sort', 'name'], 'verbose_name_plural': 'Chosen Products'},
        ),
        migrations.AddField(
            model_name='chosenproduct',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
