# Generated by Django 5.1.5 on 2025-02-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chosenproduct_options_chosenproduct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='chosenproduct',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ChosenProduct',
        ),
    ]
