# Generated by Django 5.1.5 on 2025-02-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_footerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='opening_hours',
        ),
    ]
