# Generated by Django 5.1.5 on 2025-03-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_testimonial_is_appropriate_testimonial_is_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
