# Generated by Django 5.1.5 on 2025-03-26 21:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='like_info',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
        ),
    ]
