# Generated by Django 5.1.5 on 2025-03-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_footerinfo_like_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='international_order',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='wishlist',
        ),
    ]
