# Generated by Django 5.1.5 on 2025-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/categories'),
        ),
    ]
