# Generated by Django 5.1.5 on 2025-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenproduct',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
