# Generated by Django 5.1.5 on 2025-03-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_chosenproduct_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenproduct',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
