# Generated by Django 5.1.5 on 2025-03-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
