# Generated by Django 5.1.5 on 2025-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_chosenproduct_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='will_be_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
